# VM 2 is the production worker in this cluster.
nodeSelector:
    kubernetes.io/hostname: homelab-vm2

secret:
    name: andrearcaina-site-secrets

resources:
    requests:
        cpu: 10m
        memory: 32Mi
    limits:
        cpu: 200m
        memory: 256Mi

ingress:
    enabled: true
    className: traefik
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
        - andrearcaina.ca
        - www.andrearcaina.ca
        - api.andrearcaina.ca
    path: /
