apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "site.fullname" . }}
    labels:
        {{- include "site.labels" . | nindent 8 }}
    annotations:
        {{- toYaml .Values.ingress.annotations | nindent 8 }}
spec:
    ingressClassName: {{ .Values.ingress.className }}
    tls:
        - hosts:
            {{- toYaml .Values.ingress.hosts | nindent 12 }}
    rules:
        {{- range .Values.ingress.hosts }}
        - host: {{ . | quote }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ include "site.fullname" $ }}
                            port:
                                name: http
        {{- end }}
