apiVersion: v1
kind: Service
metadata:
    name: {{ include "site.fullname" . }}
    labels:
        {{- include "site.labels" . | nindent 8 }}
spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/name: {{ include "site.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
        - name: http
          port: 8080
          targetPort: http
          protocol: TCP
