'use client';
export { default as Footer } from './general/footer';
export { default as Navbar } from './general/navbar';
export { default as Title } from './homepage/title';
export { default as Blockquote } from './homepage/blockquote';
export { default as Description } from './homepage/description';
export { default as Activities } from './homepage/activities';
export { default as Interests } from './aboutpage/interests';
export { default as Code } from './aboutpage/code';
export { default as Vim } from './aboutpage/vim';
export { default as Display } from './projectpage/display';